# Generated by Django 4.2.2 on 2023-06-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostEight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=3)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=3)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=3)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostNine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=3)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=3)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=3)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=3)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=3)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
