# Generated by Django 4.2.2 on 2023-06-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0002_blogposteight_blogpostfive_blogpostfour_blogpostnine_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.AddField(
            model_name='blogposteight',
            name='img_path',
            field=models.CharField(default='../static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostfive',
            name='img_path',
            field=models.CharField(default='../static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostfour',
            name='img_path',
            field=models.CharField(default='../static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostnine',
            name='img_path',
            field=models.CharField(default='../static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostone',
            name='img_path',
            field=models.CharField(default='../static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostseven',
            name='img_path',
            field=models.CharField(default='../static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostsix',
            name='img_path',
            field=models.CharField(default='../static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostthree',
            name='img_path',
            field=models.CharField(default='../static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogposttwo',
            name='img_path',
            field=models.CharField(default='../static/img/img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogposteight',
            name='index',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='blogpostfive',
            name='index',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='blogpostfour',
            name='index',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='blogpostnine',
            name='index',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='blogpostone',
            name='index',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='blogpostseven',
            name='index',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='blogpostsix',
            name='index',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='blogpostthree',
            name='index',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='blogposttwo',
            name='index',
            field=models.CharField(max_length=5),
        ),
    ]
