# Generated by Django 4.2.2 on 2023-06-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0003_delete_uploadimage_blogposteight_img_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposteight',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='blogpostfive',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='blogpostfour',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='blogpostnine',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='blogpostone',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='blogpostseven',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='blogpostsix',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='blogpostthree',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='blogposttwo',
            name='img_path',
        ),
        migrations.AddField(
            model_name='blogposteight',
            name='img_path_1',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogposteight',
            name='img_path_2',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogposteight',
            name='img_path_3',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostfive',
            name='img_path_1',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostfive',
            name='img_path_2',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostfive',
            name='img_path_3',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostfour',
            name='img_path_1',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostfour',
            name='img_path_2',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostfour',
            name='img_path_3',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostnine',
            name='img_path_1',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostnine',
            name='img_path_2',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostnine',
            name='img_path_3',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostone',
            name='img_path_1',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostone',
            name='img_path_2',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostone',
            name='img_path_3',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostseven',
            name='img_path_1',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostseven',
            name='img_path_2',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostseven',
            name='img_path_3',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostsix',
            name='img_path_1',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostsix',
            name='img_path_2',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostsix',
            name='img_path_3',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostthree',
            name='img_path_1',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostthree',
            name='img_path_2',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpostthree',
            name='img_path_3',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogposttwo',
            name='img_path_1',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogposttwo',
            name='img_path_2',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='blogposttwo',
            name='img_path_3',
            field=models.CharField(default='./static/img/img2.jpg', max_length=100),
        ),
    ]
