# Generated by Django 4.2.2 on 2023-06-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0004_remove_blogposteight_img_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposteight',
            name='title',
            field=models.TextField(default='This is the Title'),
        ),
        migrations.AddField(
            model_name='blogpostfive',
            name='title',
            field=models.TextField(default='This is the Title'),
        ),
        migrations.AddField(
            model_name='blogpostfour',
            name='title',
            field=models.TextField(default='This is the Title'),
        ),
        migrations.AddField(
            model_name='blogpostnine',
            name='title',
            field=models.TextField(default='This is the Title'),
        ),
        migrations.AddField(
            model_name='blogpostone',
            name='title',
            field=models.TextField(default='This is the Title'),
        ),
        migrations.AddField(
            model_name='blogpostseven',
            name='title',
            field=models.TextField(default='This is the Title'),
        ),
        migrations.AddField(
            model_name='blogpostsix',
            name='title',
            field=models.TextField(default='This is the Title'),
        ),
        migrations.AddField(
            model_name='blogpostthree',
            name='title',
            field=models.TextField(default='This is the Title'),
        ),
        migrations.AddField(
            model_name='blogposttwo',
            name='title',
            field=models.TextField(default='This is the Title'),
        ),
    ]
