# Generated by Django 4.2.2 on 2023-07-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0006_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostfour',
            name='affiliate_link',
            field=models.TextField(default='https://www.amazon.in/'),
        ),
        migrations.AddField(
            model_name='blogpostfour',
            name='img_1',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='blogpostfour',
            name='img_2',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='blogpostfour',
            name='img_3',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='blogpostthree',
            name='affiliate_link',
            field=models.TextField(default='https://www.amazon.in/'),
        ),
        migrations.AddField(
            model_name='blogpostthree',
            name='img_1',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='blogpostthree',
            name='img_2',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='blogpostthree',
            name='img_3',
            field=models.ImageField(null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='blogpostfour',
            name='description',
            field=models.TextField(default='This is default text field'),
        ),
        migrations.AlterField(
            model_name='blogpostthree',
            name='description',
            field=models.TextField(default='This is default text field'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_Main_Img',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
