# Generated by Django 4.2.2 on 2023-07-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloghome', '0008_delete_hotel_blogposteight_affiliate_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposteight',
            name='img_path_1',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogposteight',
            name='img_path_2',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogposteight',
            name='img_path_3',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostfive',
            name='img_path_1',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostfive',
            name='img_path_2',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostfive',
            name='img_path_3',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostfour',
            name='img_path_1',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostfour',
            name='img_path_2',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostfour',
            name='img_path_3',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostnine',
            name='img_path_1',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostnine',
            name='img_path_2',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostnine',
            name='img_path_3',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostone',
            name='img_path_1',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostone',
            name='img_path_2',
            field=models.CharField(default='.img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostone',
            name='img_path_3',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostseven',
            name='img_path_1',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostseven',
            name='img_path_2',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostseven',
            name='img_path_3',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostsix',
            name='img_path_1',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostsix',
            name='img_path_2',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostsix',
            name='img_path_3',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostthree',
            name='img_path_1',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostthree',
            name='img_path_2',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpostthree',
            name='img_path_3',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogposttwo',
            name='img_path_1',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogposttwo',
            name='img_path_2',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogposttwo',
            name='img_path_3',
            field=models.CharField(default='img2.jpg', max_length=100),
        ),
    ]
